---
title: FAQ
---


The DataScientia team is at your disposal for any questions related to technical aspects, clarifications or possible collaborations. [Contact Us](https://datascientia.disi.unitn.it/contact/).


## 1. Data catalog search and navigation


### What is the LivePeople catalog?

See the [catalog description](catalog.qmd).

### Why are you not distributing your data through one of the existing data catalogs?

Current data catalogs are not designed to distribute person-centric data at our granularity level, thus requiring custom procedures. To reduce the risk of re-identification or abuse, the data are shared only for research purposes with identified researchers. The current procedure has been designed with legal and privacy experts.


### What is the difference between datasets, bundles and projects?

See the [dataset organization](catalog.qmd#dataset-organization).

### Why are the datasets organized into datasets, bundles and projects?

Based on the GDPR minimization principle, data must be adequate, limited, and relevant for the analysis.  Thus, data from measurement instruments, such as accelerometer and time diaries, are provided separately. Researchers can request access to a single dataset of a specific data collection (e.g., WiFi networks in Italy in the DiversityOne data collection) or a combination of datasets from multiple data collection or sensors. To streamline dataset selection and download, we have created thematic bundles that group data commonly used together for key research purposes. For instance, activity recognition studies can download the motion bundle grouping accelerometer, activities, step counter and others. Another bundle is tailored for studying social interaction and combines questionnaires, time diaries, and location data. The catalog lists both bundles and datasets containing one single sensor.

### What is the meaning of the metadata?

The metadata provides information about the dataset and allows the data consumers to understand whether it fits their needs or research questions. The [metadata glossary](metadata.qmd) describes them.


---


## 2. Data upload and custom catalog

You can upload your [metadata values](metadata.qmd) and/or your data to our catalog. 


### Why should I create my catalog?

You can create your own instance of the catalog to redistribute data that you own. This will allow you to join the Datascientia network and increase the visibility of your data. [Contact us](https://datascientia.disi.unitn.it/contact/) if you have additional questions or if you want to join the community.

### How can I create my own data catalog?

[DataScientia foundation](https://datascientia.eu/) provides a data catalog template, built on top of [JKAN](https://jkan.io/), which can be customized to your needs. [Contact DataScientia](https://datascientia.disi.unitn.it/contact/) to get the template, and become part of the community with your catalog.

### Why should I upload my metadata and/or data on your catalog?

This allows you to make your data more visible and, if you want, leverage our data distribution procedure.

### How can I upload my own data?

[Contact](https://datascientia.disi.unitn.it/contact/) us and we will provide the detailed steps. In summary, you need to provide the metadata values, data documentation, license, and how interested data consumers can download the data.

### Can I organize a data collection using your infrastructure and/or services?
Yes, we support you in designing the study and provide access to our services. [Contact us](https://datascientia.disi.unitn.it/contact/) and describe what study you would like to organize.

